import math
g=1
a=1
b=1
i=1
y=1
x=1
z=1
x1=1
z1=1
ans=1
p=int(input("Enter the value of p:"))
for i in range(2,p-2):
  y=(p-1)/2
  ans=math.pow(i,y)
  ans=ans%p
  if(ans!=1):
    g=i
    bre ak
print(  "Value of generator is",g)
a=int(  input("Enter the private key of Alice"))
b=int(  input("Enter the private key of Bob"))
x=math  .pow(g,a)
x=x %p
z=  math.pow(g,b)
z=  z%p
pr  int("Secret key generated by Alice is",x)
print("Secret key generated by Bob is",z)
x1=math.pow(x,b)
x1=x1%p
z1=math.pow(z,a)
z1=z1%p
print("Secret key generated by Alice after exchange is",x1)
print("Secret key generated by Bob after exchange is",z1)
if(x1==z1):
  print("Transm   ission successful")
e   lse:
      print("Transmission faile                   d")

  Output of successful transmission:
    Enter the value of p: 11
    Value of generator is 2
    Enter the private key of Alice 8
    Enter the private key of Bob 9
    Secret key generated by Alice is 3.0
    Secret key generated by Bob is 6.0
    Secret key generated by Alice after exchange is 4.0
    Secret key generated by Bob after exchange is 4.0
    Transmission successful
  
  Output of unsuccessful transmission:
    Enter the value of p: 123
    Value of generator is 2
    Enter the private key of Alice 45
    Enter the private key of Bob 67
    Secret key generated by Alice is 32.0
    Secret key generated by Bob is 5.0
    Secret key generated by Alice after exchange is 50.0
    Secret key generated by Bob after exchange is 2.0
    Transmission failed  
